---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop simple-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm simple-container
      ignore_errors: yes

    - name: remove simple-project image
      command: docker rmi simple-project.img 
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t simple-project.img .

    - name: Push Image to dockerhub
      command: docker push hadijaber97/images-ready:latest

    - name: run container
      command: docker run -d --name simple-container -p 5000:80 simple-project.img